create table if not exists public.events (
  id uuid primary key default gen_random_uuid(),
  creator_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  info text null,
  event_type text not null,
  event_date date not null,
  event_time time not null,
  price_text text null,
  location_text text null,
  visibility text not null check (visibility in ('open', 'invite_only')) default 'open',
  invite_code text null,
  created_at timestamptz not null default now()
);

create index if not exists events_creator_id_idx on public.events(creator_id);
create index if not exists events_created_at_idx on public.events(created_at desc);
create index if not exists events_visibility_idx on public.events(visibility);

create table if not exists public.event_media (
  id bigint generated by default as identity primary key,
  event_id uuid not null references public.events(id) on delete cascade,
  url text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists event_media_event_id_idx on public.event_media(event_id);

create table if not exists public.event_attendees (
  event_id uuid not null references public.events(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  invite_code text null,
  joined_at timestamptz not null default now(),
  primary key (event_id, user_id)
);

create index if not exists event_attendees_user_id_idx on public.event_attendees(user_id);

alter table public.events enable row level security;
alter table public.event_media enable row level security;
alter table public.event_attendees enable row level security;

create or replace function public.is_admin_or_moderator(uid uuid)
returns boolean
language sql
stable
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = uid
      and p.role in ('admin', 'moderator')
  );
$$;

drop policy if exists events_select_accessible on public.events;
create policy events_select_accessible
on public.events
for select
to authenticated
using (
  visibility = 'open'
  or creator_id = auth.uid()
  or public.is_admin_or_moderator(auth.uid())
  or exists (
    select 1 from public.event_attendees ea
    where ea.event_id = id
      and ea.user_id = auth.uid()
  )
);

drop policy if exists events_insert_owner_or_staff on public.events;
create policy events_insert_owner_or_staff
on public.events
for insert
to authenticated
with check (
  creator_id = auth.uid()
  or public.is_admin_or_moderator(auth.uid())
);

drop policy if exists events_update_owner_or_staff on public.events;
create policy events_update_owner_or_staff
on public.events
for update
to authenticated
using (
  creator_id = auth.uid()
  or public.is_admin_or_moderator(auth.uid())
)
with check (
  creator_id = auth.uid()
  or public.is_admin_or_moderator(auth.uid())
);

drop policy if exists events_delete_owner_or_staff on public.events;
create policy events_delete_owner_or_staff
on public.events
for delete
to authenticated
using (
  creator_id = auth.uid()
  or public.is_admin_or_moderator(auth.uid())
);

drop policy if exists event_media_select_accessible on public.event_media;
create policy event_media_select_accessible
on public.event_media
for select
to authenticated
using (
  exists (
    select 1 from public.events e
    where e.id = event_id
      and (
        e.visibility = 'open'
        or e.creator_id = auth.uid()
        or public.is_admin_or_moderator(auth.uid())
        or exists (
          select 1 from public.event_attendees ea
          where ea.event_id = e.id and ea.user_id = auth.uid()
        )
      )
  )
);

drop policy if exists event_media_insert_owner_or_staff on public.event_media;
create policy event_media_insert_owner_or_staff
on public.event_media
for insert
to authenticated
with check (
  exists (
    select 1 from public.events e
    where e.id = event_id
      and (
        e.creator_id = auth.uid()
        or public.is_admin_or_moderator(auth.uid())
      )
  )
);

drop policy if exists event_media_delete_owner_or_staff on public.event_media;
create policy event_media_delete_owner_or_staff
on public.event_media
for delete
to authenticated
using (
  exists (
    select 1 from public.events e
    where e.id = event_id
      and (
        e.creator_id = auth.uid()
        or public.is_admin_or_moderator(auth.uid())
      )
  )
);

drop policy if exists event_attendees_select_related on public.event_attendees;
create policy event_attendees_select_related
on public.event_attendees
for select
to authenticated
using (
  user_id = auth.uid()
  or public.is_admin_or_moderator(auth.uid())
  or exists (
    select 1 from public.events e
    where e.id = event_id
      and e.creator_id = auth.uid()
  )
);

drop policy if exists event_attendees_insert_join_or_staff on public.event_attendees;
create policy event_attendees_insert_join_or_staff
on public.event_attendees
for insert
to authenticated
with check (
  public.is_admin_or_moderator(auth.uid())
  or (
    user_id = auth.uid()
    and exists (
      select 1 from public.events e
      where e.id = event_id
        and (
          e.visibility = 'open'
          or (e.visibility = 'invite_only' and coalesce(invite_code, '') = coalesce(e.invite_code, ''))
          or e.creator_id = auth.uid()
        )
    )
  )
);

drop policy if exists event_attendees_delete_self_or_staff on public.event_attendees;
create policy event_attendees_delete_self_or_staff
on public.event_attendees
for delete
to authenticated
using (
  user_id = auth.uid()
  or public.is_admin_or_moderator(auth.uid())
  or exists (
    select 1 from public.events e
    where e.id = event_id
      and e.creator_id = auth.uid()
  )
);
